version: '2'
services:
    incomecalculator-app:
        image: incomecalculator
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://incomecalculator-mysql:3306/incomecalculator?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    incomecalculator-mysql:
        extends:
            file: mysql.yml
            service: incomecalculator-mysql
